HTTPServer: Dynamically create and clean up XDG dirs on each request if not exists
If the `XDG_CACHE_HOME` and/or `XDG_CONFIG_HOME` env vars are not set, we create a temp dir per requests to protect tenant boundary and delete it up when the request finishes.

Fixes https://github.com/grafana/grafana-image-renderer/issues/748

It was noted that in some Linux environments such as OpenShift, the lack of those environment variables caused a crash in Chromium when attempting to render:
```
Otherwise errors like this one would happen:

  Error: Failed to launch the browser process!
  chrome_crashpad_handler: --database is required
```